#TODO: Add connections to PlanetScale database in here
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

#TODO: Use environmnet variables here then add them to here on aws side
jwt:
  key: ${JWT_KEY}`